import {
    faBars,
    faFilter,
    faChevronDown,
    faUser,
    faThumbsUp,
    faThumbsDown,
    faXmark,
    faPlus,
    faMagnifyingGlass,
    faCaretDown,
    faChevronLeft,
    faChevronRight,
    faEye,
    faSun,
    faMoon,
    faComment,
    faShareFromSquare,
    faLink,
} from "@fortawesome/free-solid-svg-icons";
import { faCircleXmark, faCircleCheck } from "@fortawesome/free-regular-svg-icons";
import { faTelegram, faInstagramSquare, faVk, faFacebook } from "@fortawesome/free-brands-svg-icons";

export const icons = [
    faBars,
    faFilter,
    faChevronDown,
    faUser,
    faThumbsUp,
    faThumbsDown,
    faXmark,
    faPlus,
    faTelegram,
    faInstagramSquare,
    faVk,
    faFacebook,
    faCircleXmark,
    faCircleCheck,
    faMagnifyingGlass,
    faCaretDown,
    faChevronLeft,
    faChevronRight,
    faEye,
    faSun,
    faMoon,
    faComment,
    faShareFromSquare,
    faLink,
];
